name: WakaTime status update 

on:
  workflow_dispatch:
  schedule:
    - cron: '1 0 * * 6'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ github.token }}
          COMMIT_MESSAGE: "chore: WakaTime Update :alien:"
